### ISSUE TITLE
Context menu on hold

### ISSUE THREAD

**Issue by tinybigideas** [ilmente/mnTouch#12]
Using:

```
nm-touch touch="function()"
```

And this works to trigger the relevant function, although, the right mouse context menu also appears. Have you seen this happen before? The hold event itself is just on a div containing an image.

Happens on both desktop, and mobile Chrome.

Any help would be brilliant.

Thanks!

**Comment by ilmente** [comment]
Hi @tinybigideas,
no, never happened to me, but I can check!
Thanks, I'll let you know!

**Comment by ilmente** [comment]
Hi @tinybigideas,
it's been a while since last time... I'm sorry.
I just released the `1.3.0` version and I did some test: context menu appear if you try to hold on something that does't have a hold event handler; at least, this is what I figured out. If you add and handler, context menu should't appear.

Hope to be in time, but I have some doubts. 
Thanks.

Best.
